### ISSUE TITLE
Ai and EPS thumbnail creation returns "returned non-zero exit status 1"

### ISSUE THREAD

**Issue by stm-clemens** [algoo/preview-generator#102]
Hey,

I want to generate thumbnails from vector files such as ai and eps.

as soon as I want to "convert" one i get the following Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 57, in <module>
    preview_ = manager.get_jpeg_preview(image_, width=1024, height=1024, force=True, file_ext=os.path.splitext(image_)[1])
  File "/usr/local/lib/python3.6/dist-packages/preview_generator/manager.py", line 176, in get_jpeg_preview
    mimetype=mimetype,
  File "/usr/local/lib/python3.6/dist-packages/preview_generator/preview/builder/image__imconvert.py", line 86, in build_jpeg_preview
    ["convert", file_path, "-layers", "merge", tmp_filepath], stdout=DEVNULL, stderr=STDOUT
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['convert', '/src/filecrawler/filecrawler/test_dir/orig/Osterei.ai', '-layers', 'merge', '/tmp/6cd5bfa9-06c3-43cd-9d43-2695ccd1f954.png']' returned non-zero exit status 1.

```

**Comment by inkhey** [comment]
@stm-clemens Hello, Thanks for the issue.
I tried with another .ai but can't reproduce issue, so it's seems related to some specific .ai file.

Can you provide origin image which cause issue ?

if that's not possible for some reason, we will need to result of : 
`
convert /src/filecrawler/filecrawler/test_dir/orig/Osterei.ai -layers merge /tmp/6cd5bfa9-06c3-43cd-9d43-2695ccd1f954.png
`
command (you can directly run this in bash) . You may have this way some extra information about why the process failed in imagemagick.

**Comment by stm-clemens** [comment]
Hey thanks for you answer,

with that command I get the following error:
```
convert-im6.q16: not authorized `/src/filecrawler/filecrawler/test_dir/orig/Osterei.ai' @ error/constitute.c/ReadImage/412.
convert-im6.q16: no images defined `/tmp/6cd5bfa9-06c3-43cd-9d43-2695ccd1f954.png' @ error/convert.c/ConvertImageCommand/3258.
```

I attached the ai file. I had to zip it due to allowed filetypes.

[Osterei.ai.zip](https://github.com/algoo/preview-generator/files/3417162/Osterei.ai.zip)

**Comment by inkhey** [comment]
Tried to convert it locally and it work on my system.
It seems related to ImageMagick config.
ImageMagick has a "policy" file which block some format conversion for security reasons. Content of this file can be very different on differents system.
Mine (on debian 9) was located in` /etc/ImageMagick-6/policy.xml`.
Can you check your policy file ?
You can post his content here and/or try yourself to delete/comment some policy.
If you found a policy which cause the issue, please post it here, in order to help us documentate how to overcome these issue for future users.

PS, article about the issue:
https://cromwell-intl.com/open-source/pdf-not-authorized.html

**Comment by stm-clemens** [comment]
Thanks,
I got It working.
I had to add fields to the policy for my vector files with read and write.

Another Problem which I had was that ufraw (Imagemagick) was unable to process my orf RAW file. Its from a fairly new camera (3 Years old Olympus E-M1 Mark II) it always told me 
```
convert-im6.q16: FailedToExecuteCommand `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=/tmp/magick-3373TgfWyYgkdjaS.png' '/tmp/magick-3373D7sm1dzdZJ9H'' (-1) @ error/delegate.c/ExternalDelegateCommand/462. convert-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1919.
```
I didnt get it to work. I used a comparsion to use a self written process with dcraw  to convert my raw files (with extract thumbnail from raw file) . Shrink it in size and dpi and save it.
It may be not the best solution using os.system but its working.

ORF Raw attached if you want to try it yourself. That RAW file is from mirrorlesscomparison.com
[_OMD5031.ORF.zip](https://github.com/algoo/preview-generator/files/3430389/_OMD5031.ORF.zip)

**Comment by inkhey** [comment]
Are you sure to have installed ufraw ?
Imagemagick need ufraw-batch working command to be able to support raw file.
package in debian (and probably ubuntu ) is called ufraw.

`
sudo apt install ufraw
`

you can also try direcly convert using ufraw-batch: 

`
ufraw-batch --silent --create-id=also --out-type=png --out-depth=16 --output=test.png _OMD5031.ORF
`
and copy paste result here directly.
Be carefull, this create a very big png file (around 98mo on my system).

**Comment by stm-clemens** [comment]
yeah I am sure,
I just checked my installed packages
```
root@c58eec4c71b1:/src/filecrawler/filecrawler# dpkg -s ufraw
Package: ufraw
Status: install ok installed
```

I tired to run that command directly and i had the same issue. maybe apt installs an old version on ubuntu?

I think my version with extracting the thumbnail from the raw is more elegant because you don't have to fiddle with the raw settings. And the file I have to work with is much smaller.
maybe you want to incoperate dcraw or libraw with dcraw_emu. Thumbnail extraction and processing takes no time at all not even a second.

**Comment by inkhey** [comment]
> yeah I am sure,
> I just checked my installed packages
> 
> ```
> root@c58eec4c71b1:/src/filecrawler/filecrawler# dpkg -s ufraw
> Package: ufraw
> Status: install ok installed
> ```
> 
> I tired to run that command directly and i had the same issue. maybe apt installs an old version on ubuntu?

Try to get ufraw-batch version : `ufraw-batch --version`  and copy-paste result.
I got this:
```
 ❯ ufraw-batch --version
ufraw-batch 0.22
EXIV2 enabled.
JPEG enabled.
JPEG2000 (libjasper) disabled.
TIFF enabled.
PNG enabled.
FITS disabled.
ZIP enabled.
BZIP2 enabled.
LENSFUN enabled.

```
If this doesn't answered at all this may mean that ufraw-batch is in another package or just isn't packaged at all. In other case you should probably get some error with explicit message.


> I think my version with extracting the thumbnail from the raw is more elegant because you don't have to fiddle with the raw settings. And the file I have to work with is much smaller.
> maybe you want to incoperate dcraw or libraw with dcraw_emu. Thumbnail extraction and processing takes no time at all not even a second.

It's effectlively a good idea. we should add a builder for dcraw (or other software that is able to make effective preview of raw file) and configure code to have priority for raw file on imagemagick/ufraw, this way we can have a fallback on imagemagick if dcraw isn't installed.

**Comment by stm-clemens** [comment]
```
ufraw-batch --version
ufraw-batch 0.22
EXIV2 enabled.
JPEG enabled.
JPEG2000 (libjasper) disabled.
TIFF enabled.
PNG enabled.
FITS disabled.
ZIP enabled.
BZIP2 enabled.
LENSFUN enabled.
```
Thats the output. Looks the same. Strange issue.

**Comment by inkhey** [comment]
@stm-clemens 
can you delete potential test.png file and redo:

`ufraw-batch --silent --create-id=also --out-type=png --out-depth=16 --output=test.png _OMD5031.ORF`

and immediatly after, type:

`echo $?`

and them copy paste all command and result here .
like :
 ❯ ufraw-batch --silent --create-id=also --out-type=png --out-depth=16 --output=test.png _OMD5031.ORF
 ❯ echo $?
0

**Comment by stm-clemens** [comment]
```
root@c58eec4c71b1:/src/filecrawler/filecrawler# ufraw-batch --silent --create-id=also --out-type=png --out-depth=16 --output=test.png _OMD5031.ORF
Segmentation fault
root@c58eec4c71b1:/src/filecrawler/filecrawler# echo $?
139
```

Thats the Output. Its creating the test.png and a test.ufraw. But i get that segmentation fault.

**Comment by inkhey** [comment]
> Thats the Output. Its creating the test.png and a test.ufraw. But i get that segmentation fault.

Interesting, look like there is something broken in ufraw.

I suggest you to check your exact version of ufraw-batch package this way (i did it on my machine where ufraw do work correctly with this file) :

```
 ❯ apt show ufraw-batch | grep Version

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Version: 0.22-1.1
```

I found some issues on the internet about segmentation fault in ufraw, like this one (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898297)  but i'm not sure if this match our case.

**Comment by stm-clemens** [comment]
```
root@c58eec4c71b1:/src/filecrawler/filecrawler# apt show ufraw-batch | grep Version

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Version: 0.22-3.1~build0.18.04.1
```

Is the output.

**Comment by hatcherfang** [comment]
> Hey,
> 
> I want to generate thumbnails from vector files such as ai and eps.
> 
> as soon as I want to "convert" one i get the following Error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "./__main__.py", line 57, in <module>
>     preview_ = manager.get_jpeg_preview(image_, width=1024, height=1024, force=True, file_ext=os.path.splitext(image_)[1])
>   File "/usr/local/lib/python3.6/dist-packages/preview_generator/manager.py", line 176, in get_jpeg_preview
>     mimetype=mimetype,
>   File "/usr/local/lib/python3.6/dist-packages/preview_generator/preview/builder/image__imconvert.py", line 86, in build_jpeg_preview
>     ["convert", file_path, "-layers", "merge", tmp_filepath], stdout=DEVNULL, stderr=STDOUT
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['convert', '/src/filecrawler/filecrawler/test_dir/orig/Osterei.ai', '-layers', 'merge', '/tmp/6cd5bfa9-06c3-43cd-9d43-2695ccd1f954.png']' returned non-zero exit status 1.
> ```

I get the same exception when i  try to produce the png picture thumnai, and finally i solved it by set the parameter file_ext for function "manager.get_jpeg_preview". the test code as below:
```
from preview_generator.manager import PreviewManager                                  
                                                                                                                                                                     
path = './IMG20200422_094758.png'
manager = PreviewManager(cache_path, create_folder=True)                              
path_to_preview_image = manager.get_jpeg_preview(path, width=400, height=400, file_ext='.jpeg', force=True)
```
You can try to set file_ext value to solve your case.
