### ISSUE TITLE
Pip3 Install: "No such file or directory: 'exiftool'"

### ISSUE THREAD

**Issue by kylemart** [algoo/preview-generator#173]
I'm running into the following error when trying to install preview-generator with pip3:

```
~
❯ pip3 install preview-generator
Collecting preview-generator
  Downloading https://files.pythonhosted.org/packages/e6/ef/5c0af4350ead9b38071f0aa48addf57a40dcb42575b829318dda7dd54895/preview_generator-0.13.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 2.6MB/s
Collecting python-magic (from preview-generator)
  Downloading https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting Wand (from preview-generator)
  Downloading https://files.pythonhosted.org/packages/ad/4a/6d4897ce1c6640c0669829d34cdf956e0829281b3f94c71effdb23bdde3c/Wand-0.5.8-py2.py3-none-any.whl (129kB)
    100% |████████████████████████████████| 133kB 6.0MB/s
Collecting PyPDF2 (from preview-generator)
  Downloading https://files.pythonhosted.org/packages/b4/01/68fcc0d43daf4c6bdbc6b33cc3f77bda531c86b174cac56ef0ffdb96faab/PyPDF2-1.26.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 20.8MB/s
Collecting Pillow (from preview-generator)
  Downloading https://files.pythonhosted.org/packages/0c/43/b52847e473ac6cbd10a749b63018b2bb08b55c6e1a1923872361443906de/Pillow-7.0.0-cp37-cp37m-macosx_10_6_intel.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 11.6MB/s
Collecting pyexifinfo (from preview-generator)
  Downloading https://files.pythonhosted.org/packages/d5/57/7d90277921541ff7113ec1de13b7163f9b85abe43f905a9f94420ecdd528/pyexifinfo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyexifinfo.egg-info
    writing pip-egg-info/pyexifinfo.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pyexifinfo.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/pyexifinfo.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hj/_h2j01n96k17z5h7f3zsy7sm0000gn/T/pip-install-of_352sd/pyexifinfo/setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "/private/var/folders/hj/_h2j01n96k17z5h7f3zsy7sm0000gn/T/pip-install-of_352sd/pyexifinfo/setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'exiftool': 'exiftool'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hj/_h2j01n96k17z5h7f3zsy7sm0000gn/T/pip-install-of_352sd/pyexifinfo/
```

**Comment by kylemart** [comment]
Ended up installing exiftool with `brew install exiftool`. That fixed the issue.

**Comment by inkhey** [comment]
related to #241 
@kylemart be free to propose PR with document about how to install preview-generator on MacOSX
