### ISSUE TITLE
don't work on MacOS

### ISSUE THREAD

**Issue by goldenstar8080** [algoo/preview-generator#85]
This package don't work on MacOS. 
By my guess, I think this package run `libreoffice` command. It's ok on Ubuntu OS. But it's failed on MacOS. I think it must use `soffice` command instead of `libreoffice` on MacOS.
I'll be happy if you help and assist me for usage of this package on MacOS.

**my codes**
```
from preview_generator.manager import PreviewManager

HEIGHT = 1024
WIDTH = 526
PAGE_ID = 1

def pdf_to_image(cach_dir_path, pdf_file_path, font_path=None):
    preview_manager = PreviewManager(cach_dir_path, create_folder=True)
    preview = preview_manager.get_jpeg_preview(pdf_file_path, height=HEIGHT, width=WIDTH)
    return preview
```

**Then I had these issues**
```
--- Logging error ---
Traceback (most recent call last):
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/utils.py", line 136, in check_executable_is_available
    stderr=STDOUT
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice': 'libreoffice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    response = self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
    response = self._middleware_chain(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 281, in put
    preview = self.convert_pdf_to_image(full_dir, preview)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 203, in convert_pdf_to_image
    return pdf_to_image(cach_dir_path, file_path)
  File "/Volumes/Data/work/alaric/new/headshot-backend/converter/pdf2jpg.py", line 21, in pdf_to_image
    preview_manager = PreviewManager(cach_dir_path, create_folder=True)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/manager.py", line 34, in __init__
    self._factory = PreviewBuilderFactory.get_instance()  # nopep8 keep link to singleton instance as it will be often used
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 112, in get_instance
    cls._instance.load_builders()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 101, in load_builders
    self.register_builder(cls)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 118, in register_builder
    builder.check_dependencies()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder/office__libreoffice.py", line 37, in check_dependencies
    return check_executable_is_available('libreoffice')
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/utils.py", line 143, in check_executable_is_available
    logger.error('Error while checking dependencies: ', e)
Message: 'Error while checking dependencies: '
Arguments: (FileNotFoundError(2, "No such file or directory: 'libreoffice'"),)
Builder <class 'preview_generator.preview.builder.office__libreoffice.OfficePreviewBuilderLibreoffice'> is missing a dependency: this builder requires libreoffice to be available
--- Logging error ---
Traceback (most recent call last):
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/utils.py", line 136, in check_executable_is_available
    stderr=STDOUT
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice': 'libreoffice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    response = self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
    response = self._middleware_chain(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 281, in put
    preview = self.convert_pdf_to_image(full_dir, preview)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 203, in convert_pdf_to_image
    return pdf_to_image(cach_dir_path, file_path)
  File "/Volumes/Data/work/alaric/new/headshot-backend/converter/pdf2jpg.py", line 21, in pdf_to_image
    preview_manager = PreviewManager(cach_dir_path, create_folder=True)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/manager.py", line 34, in __init__
    self._factory = PreviewBuilderFactory.get_instance()  # nopep8 keep link to singleton instance as it will be often used
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 112, in get_instance
    cls._instance.load_builders()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 101, in load_builders
    self.register_builder(cls)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder_factory.py", line 118, in register_builder
    builder.check_dependencies()
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder/office__libreoffice.py", line 37, in check_dependencies
    return check_executable_is_available('libreoffice')
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/utils.py", line 143, in check_executable_is_available
    logger.error('Error while checking dependencies: ', e)
Message: 'Error while checking dependencies: '
Arguments: (FileNotFoundError(2, "No such file or directory: 'libreoffice'"),)
Builder <class 'preview_generator.preview.builder.plain_text.PlainTextPreviewBuilder'> is missing a dependency: this builder requires libreoffice to be available
Builder <class 'preview_generator.preview.builder.document__scribus.DocumentPreviewBuilderScribus'> is missing a dependency: this builder requires scribus to be available
Internal Server Error: /api/v1/headshot/upload_doc/263/
Traceback (most recent call last):
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 224, in _page_count
    proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdfinfo': 'pdfinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 281, in put
    preview = self.convert_pdf_to_image(full_dir, preview)
  File "/Volumes/Data/work/alaric/new/headshot-backend/headshot/views.py", line 203, in convert_pdf_to_image
    return pdf_to_image(cach_dir_path, file_path)
  File "/Volumes/Data/work/alaric/new/headshot-backend/converter/pdf2jpg.py", line 22, in pdf_to_image
    preview = preview_manager.get_jpeg_preview(pdf_file_path, height=HEIGHT, width=WIDTH)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/manager.py", line 187, in get_jpeg_preview
    mimetype=mimetype
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder/pdf__pypdf2.py", line 48, in build_jpeg_preview
    result = convert_pdf_to_jpeg(output_stream, size)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/preview_generator/preview/builder/image__wand.py", line 49, in convert_pdf_to_jpeg
    images = convert_from_bytes(pdf)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 158, in convert_from_bytes
    output_file=output_file, poppler_path=poppler_path)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 53, in convert_from_path
    page_count = _page_count(pdf_path, userpw, poppler_path=poppler_path)
  File "/Volumes/Data/work/alaric/new/headshot-backend/env3/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 228, in _page_count
    raise PDFInfoNotInstalledError('Unable to get page count. Is poppler installed and in PATH?')
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

**Comment by inkhey** [comment]
Hello,

Have you try to create a command alias here to make "libreoffice" command exist as the same as "soffice" ? It's seems to me the easiest solution to "manually" fix the issue.  We should do a better fix later, but we should be sure that's the solution.

Can you try this, and return us if this is enough to make preview_generator work on mac OS X ? ( i do not have mac os x machine, so i can't test).

**Comment by ChristelleG** [comment]
Hello

 I manage to install the library on mac and also to link libreoffice by creating a bash executable file in /usr/local/bin with just a link to soffice

I am still running into some errors :"preview_generator.exception.UnsupportedMimeType: Unsupported mimetype: application/vnd.openxmlformats-officedocument.wordprocessingml.document" - I wondered if I have other dependencies missing ?

**Comment by inkhey** [comment]
moved into the compatibility metaticket #241
